// <auto-generated>
//   This code file has automatically been added by the "Bannerlord.BUTR.Shared" NuGet package (https://www.nuget.org/packages/Bannerlord.BUTR.Shared).
//   Please see https://github.com/BUTR/Bannerlord.BUTR.Shared for more information.
//
//   IMPORTANT:
//   DO NOT DELETE THIS FILE if you are using a "packages.config" file to manage your NuGet references.
//   Consider migrating to PackageReferences instead:
//   https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference
//   Migrating brings the following benefits:
//   * The "Bannerlord.BUTR.Shared" folder and the "Bannerlord.BUTR.Shared.cs" file don't appear in your project.
//   * The added file is immutable and can therefore not be modified by coincidence.
//   * Updating/Uninstalling the package will work flawlessly.
// </auto-generated>

#region License
// MIT License
// 
// Copyright (c) Bannerlord's Unofficial Tools & Resources
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#endregion

#if !BANNERLORDBUTRSHARED_DISABLE
#nullable enable
#pragma warning disable

namespace Bannerlord.BUTR.Shared.Helpers
{
    using global::System.Diagnostics;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Xml;
    using global::System.Reflection;
    using global::System.IO;

    using global::TaleWorlds.Library;

#if !BANNERLORDBUTRSHARED_INCLUDE_IN_CODE_COVERAGE
    [ExcludeFromCodeCoverage, DebuggerNonUserCode]
#endif
    internal static class ApplicationVersionUtils
    {
        private static readonly PropertyInfo _emptyProperty = typeof(ApplicationVersion).GetProperty("Empty", BindingFlags.Public | BindingFlags.Static);
        private static readonly PropertyInfo _applicationVersionTypeProperty = typeof(ApplicationVersion).GetProperty("ApplicationVersionType", BindingFlags.Public | BindingFlags.Instance);
        private static readonly PropertyInfo _majorProperty = typeof(ApplicationVersion).GetProperty("Major", BindingFlags.Public | BindingFlags.Instance);
        private static readonly PropertyInfo _minorProperty = typeof(ApplicationVersion).GetProperty("Minor", BindingFlags.Public | BindingFlags.Instance);
        private static readonly PropertyInfo _revisionProperty = typeof(ApplicationVersion).GetProperty("Revision", BindingFlags.Public | BindingFlags.Instance);
        private static readonly PropertyInfo _changeSetProperty = typeof(ApplicationVersion).GetProperty("ChangeSet", BindingFlags.Public | BindingFlags.Instance);

        private static string GetPrefix(ApplicationVersionType applicationVersionType) => (int) applicationVersionType switch
        {
            0 => "a",
            1 => "b",
            2 => "e",
            3 => "v",
            4 => "d",
            5 => "m",
            _ => "i"
        };
        private static ApplicationVersionType ApplicationVersionTypeFromString(string applicationVersionType) => 
            string.IsNullOrEmpty(applicationVersionType) ? default : ApplicationVersionTypeFromString(applicationVersionType[0]);
        private static ApplicationVersionType ApplicationVersionTypeFromString(char applicationVersionType) => applicationVersionType switch
        {
            'a' => (ApplicationVersionType) 0,
            'b' => (ApplicationVersionType) 1,
            'e' => (ApplicationVersionType) 2,
            'v' => (ApplicationVersionType) 3,
            'd' => (ApplicationVersionType) 4,
            'm' => (ApplicationVersionType) 5,
            _ => (ApplicationVersionType) (int) -1,
        };

        private static ApplicationVersion FromParametersFile(string versionGameType)
        {
            var xmlDocument = new XmlDocument();
            xmlDocument.LoadXml(VirtualFolders.GetFileContent(Path.Combine(BasePath.Name, "Parameters", "Version.xml")));
            var versionAsString = xmlDocument?.SelectSingleNode("Version")?.SelectSingleNode(versionGameType)?.Attributes["Value"]?.InnerText;
            TryParse(versionAsString, out var version);
            return version;
        }

        public static bool TryParse(string? versionAsString, out ApplicationVersion version)
        {
            var major = 0;
            var minor = 0;
            var revision = 0;
            var changeSet = 0;
            bool skipCheck = false;
            version = default;
            if (versionAsString is null)
                return false;

            var array = versionAsString.Split('.');
            if (array.Length != 3 && array.Length != 4 && array[0].Length == 0)
                return false;

            var applicationVersionType = ApplicationVersionTypeFromString(array[0][0]);
            if (!skipCheck && !int.TryParse(array[0].Substring(1), out major))
            {
                if (array[0].Substring(1) != "*") return false;
                major = int.MinValue;
                minor = int.MinValue;
                revision = int.MinValue;
                changeSet = int.MinValue;
                skipCheck = true;
            }
            if (!skipCheck && !int.TryParse(array[1], out minor))
            {
                if (array[1] != "*") return false;
                minor = 0;
                revision = 0;
                changeSet = 0;
                skipCheck = true;
            }
            if (!skipCheck && !int.TryParse(array[2], out revision))
            {
                if (array[2] != "*") return false;
                revision = 0;
                changeSet = 0;
                skipCheck = true;
            }

            if (!skipCheck && array.Length == 4 && !int.TryParse(array[3], out changeSet))
            {
                if (array[3] != "*") return false;
                changeSet = 0;
                skipCheck = true;
            }

            object boxed = version;
            _applicationVersionTypeProperty?.SetValue(boxed, applicationVersionType);
            _majorProperty?.SetValue(boxed, major);
            _minorProperty?.SetValue(boxed, minor);
            _revisionProperty?.SetValue(boxed, revision);
            _changeSetProperty?.SetValue(boxed, changeSet);

            return true;
        }

        public static string ToString(ApplicationVersion av)
        {
            string prefix = GetPrefix(av.ApplicationVersionType);
            var def = FromParametersFile("Singleplayer");
            return $"{prefix}{av.Major}.{av.Minor}.{av.Revision}{(av.ChangeSet == def.ChangeSet ? "" : $".{av.ChangeSet}")}";
        }

        public static ApplicationVersion GetEmpty() => _emptyProperty?.GetValue(null) is ApplicationVersion av ? av : default;
    }
}

#pragma warning restore
#nullable restore
#endif // BANNERLORDBUTRSHARED_DISABLE
