// <auto-generated>
//   This code file has automatically been added by the "Bannerlord.BUTR.Shared" NuGet package (https://www.nuget.org/packages/Bannerlord.BUTR.Shared).
//   Please see https://github.com/BUTR/Bannerlord.BUTR.Shared for more information.
//
//   IMPORTANT:
//   DO NOT DELETE THIS FILE if you are using a "packages.config" file to manage your NuGet references.
//   Consider migrating to PackageReferences instead:
//   https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference
//   Migrating brings the following benefits:
//   * The "Bannerlord.BUTR.Shared/Helpers" folder and the "ApplicationVersionHelper.cs" file don't appear in your project.
//   * The added file is immutable and can therefore not be modified by coincidence.
//   * Updating/Uninstalling the package will work flawlessly.
// </auto-generated>

#region License
// MIT License
// 
// Copyright (c) Bannerlord's Unofficial Tools & Resources
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#endregion

#if !BANNERLORDBUTRSHARED_DISABLE
#nullable enable
#if !BANNERLORDBUTRSHARED_ENABLE_WARNINGS
#pragma warning disable
#endif

namespace Bannerlord.BUTR.Shared.Helpers
{
    using global::HarmonyLib.BUTR.Extensions;

    using global::System;
    using global::System.Collections.Generic;
    using global::System.Diagnostics;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Xml;
    using global::System.Reflection;
    using global::System.Runtime.Serialization;
    using global::System.IO;

    using global::TaleWorlds.DotNet;
    using global::TaleWorlds.Library;

#if !BANNERLORDBUTRSHARED_INCLUDE_IN_CODE_COVERAGE
    [ExcludeFromCodeCoverage, DebuggerNonUserCode]
#endif
    internal static class ApplicationVersionHelper
    {
        private delegate string? GetVersionStrDelegateV1();
        private delegate string? GetVersionStrDelegateV2(string str);
        
        private static readonly GetVersionStrDelegateV1? GetVersionStrV1;
        private static readonly GetVersionStrDelegateV2? GetVersionStrV2;

        private delegate void SetApplicationVersionTypeDelegate(ApplicationVersion instance, ApplicationVersionType applicationVersionType);
        private static readonly SetApplicationVersionTypeDelegate? SetApplicationVersionType;

        private delegate void SetMajorDelegate(ApplicationVersion instance, int major);
        private static readonly SetMajorDelegate? SetMajor;

        private delegate void SetMinorDelegate(ApplicationVersion instance, int minor);
        private static readonly SetMinorDelegate? SetMinor;

        private delegate void SetRevisionDelegate(ApplicationVersion instance, int revision);
        private static readonly SetRevisionDelegate? SetRevision;

        private delegate void SetChangeSetDelegate(ApplicationVersion instance, int changeSet);
        private static readonly SetChangeSetDelegate? SetChangeSet;

        private delegate void SetVersionGameTypeDelegate(ApplicationVersion instance, int versionGameType);
        private static readonly SetVersionGameTypeDelegate? SetVersionGameType;

        private delegate ApplicationVersion GetEmptyDelegate();
        private static readonly GetEmptyDelegate? GetEmpty;

        public static ApplicationVersion Empty => GetEmpty is not null ? GetEmpty() : default;

        static ApplicationVersionHelper()
        {
            SetApplicationVersionType = AccessTools2.GetPropertySetterDelegate<SetApplicationVersionTypeDelegate>(typeof(ApplicationVersion), "ApplicationVersionType");
            SetMajor = AccessTools2.GetPropertySetterDelegate<SetMajorDelegate>(typeof(ApplicationVersion), "Major");
            SetMinor = AccessTools2.GetPropertySetterDelegate<SetMinorDelegate>(typeof(ApplicationVersion), "Minor");
            SetRevision = AccessTools2.GetPropertySetterDelegate<SetRevisionDelegate>(typeof(ApplicationVersion), "Revision");
            SetChangeSet = AccessTools2.GetPropertySetterDelegate<SetChangeSetDelegate>(typeof(ApplicationVersion), "ChangeSet");
            SetVersionGameType = AccessTools2.GetPropertySetterDelegate<SetVersionGameTypeDelegate>(typeof(ApplicationVersion), "VersionGameType");

            GetEmpty = AccessTools2.GetPropertyGetterDelegate<GetEmptyDelegate>(typeof(ApplicationVersion), "Empty");

            if (AccessTools2.Method(typeof(Managed), "GetVersionStr", new Type[] { }) is { } v1)
                GetVersionStrV1 = AccessTools2.GetDelegate<GetVersionStrDelegateV1>(v1);
            if (AccessTools2.Method(typeof(Managed), "GetVersionStr", new Type[] { typeof(string) }) is { } v2)
                GetVersionStrV2 = AccessTools2.GetDelegate<GetVersionStrDelegateV2>(v2);
        }

        private static string GetPrefix(ApplicationVersionType applicationVersionType) => (int) applicationVersionType switch
        {
            0 => "a",
            1 => "b",
            2 => "e",
            3 => "v",
            4 => "d",
            5 => "m",
            _ => "i"
        };
        private static ApplicationVersionType ApplicationVersionTypeFromString(string applicationVersionType) =>
            string.IsNullOrEmpty(applicationVersionType) ? default : ApplicationVersionTypeFromString(applicationVersionType[0]);
        private static ApplicationVersionType ApplicationVersionTypeFromString(char applicationVersionType) => applicationVersionType switch
        {
            'a' => (ApplicationVersionType) 0,
            'b' => (ApplicationVersionType) 1,
            'e' => (ApplicationVersionType) 2,
            'v' => (ApplicationVersionType) 3,
            'd' => (ApplicationVersionType) 4,
            'm' => (ApplicationVersionType) 5,
            _ => (ApplicationVersionType) (int) -1,
        };

        public static ApplicationVersion FromParametersFile(string versionGameType)
        {
            var xmlDocument = new XmlDocument();
            xmlDocument.LoadXml(VirtualFolders.GetFileContent(Path.Combine(BasePath.Name, "Parameters", "Version.xml")));
            var versionAsString = xmlDocument?.SelectSingleNode("Version")?.SelectSingleNode(versionGameType)?.Attributes["Value"]?.InnerText;
            TryParse(versionAsString, out var version);
            return version;
        }

        public static bool TryParse(string? versionAsString, out ApplicationVersion version) => TryParse(versionAsString, out version, true);

        public static bool TryParse(string? versionAsString, out ApplicationVersion version, bool asMin)
        {
            var major = asMin ? 0 : int.MaxValue;
            var minor = asMin ? 0 : int.MaxValue;
            var revision = asMin ? 0 : int.MaxValue;
            var changeSet = asMin ? 0 : int.MaxValue;
            var skipCheck = false;
            version = Empty;
            if (versionAsString is null)
                return false;

            var array = versionAsString.Split('.');
            if (array.Length != 3 && array.Length != 4 && array[0].Length == 0)
                return false;

            var applicationVersionType = ApplicationVersionTypeFromString(array[0][0]);
            if (!skipCheck && !int.TryParse(array[0].Substring(1), out major))
            {
                if (array[0].Substring(1) != "*") return false;
                major = int.MinValue;
                minor = int.MinValue;
                revision = int.MinValue;
                changeSet = int.MinValue;
                skipCheck = true;
            }
            if (!skipCheck && !int.TryParse(array[1], out minor))
            {
                if (array[1] != "*") return false;
                minor = asMin ? 0 : int.MaxValue;
                revision = asMin ? 0 : int.MaxValue;
                changeSet = asMin ? 0 : int.MaxValue;
                skipCheck = true;
            }
            if (!skipCheck && !int.TryParse(array[2], out revision))
            {
                if (array[2] != "*") return false;
                revision = asMin ? 0 : int.MaxValue;
                changeSet = asMin ? 0 : int.MaxValue;
                skipCheck = true;
            }

            if (!skipCheck && array.Length == 4 && !int.TryParse(array[3], out changeSet))
            {
                if (array[3] != "*") return false;
                changeSet = asMin ? 0 : int.MaxValue;
                skipCheck = true;
            }

            var boxedVersion = (ApplicationVersion) FormatterServices.GetUninitializedObject(typeof(ApplicationVersion)); // https://stackoverflow.com/a/6280540
            SetApplicationVersionType?.Invoke(boxedVersion, applicationVersionType);
            SetMajor?.Invoke(boxedVersion, major);
            SetMinor?.Invoke(boxedVersion, minor);
            SetRevision?.Invoke(boxedVersion, revision);
            SetChangeSet?.Invoke(boxedVersion, changeSet);
            SetVersionGameType?.Invoke(boxedVersion, 0);
            version = (ApplicationVersion) boxedVersion;

            return true;
        }

        public static string ToString(ApplicationVersion av)
        {
            var prefix = GetPrefix(av.ApplicationVersionType);
            var def = FromParametersFile("Singleplayer");
            return $"{prefix}{av.Major}.{av.Minor}.{av.Revision}{(av.ChangeSet == def.ChangeSet ? "" : $".{av.ChangeSet}")}";
        }

        public static bool IsSame(this ApplicationVersion @this, ApplicationVersion other) =>
            @this.ApplicationVersionType == other.ApplicationVersionType &&
            @this.Major == other.Major &&
            @this.Minor == other.Minor &&
            @this.Revision == other.Revision;

        public static bool IsSameWithChangeSet(this ApplicationVersion @this, ApplicationVersion other) =>
            @this.ApplicationVersionType == other.ApplicationVersionType &&
            @this.Major == other.Major &&
            @this.Minor == other.Minor &&
            @this.Revision == other.Revision &&
            @this.ChangeSet == other.ChangeSet;

        public static ApplicationVersion? GameVersion() => TryParse(GameVersionStr(), out var v) ? v : null;

        public static string GameVersionStr()
        {
            if (GetVersionStrV1 is not null)
                return GetVersionStrV1() ?? "e1.0.0";

            if (GetVersionStrV2 is not null)
                return GetVersionStrV2("Singleplayer") ?? "e1.0.0";

            return ToString(FromParametersFile("Singleplayer"));
        }
    }

    internal class ApplicationVersionWithoutGameTypeComparer : IComparer<ApplicationVersion>
    {
        public int Compare(ApplicationVersion x, ApplicationVersion y)
        {
            var applicationVersionTypeComparison = x.ApplicationVersionType.CompareTo(y.ApplicationVersionType);
            if (applicationVersionTypeComparison != 0) return applicationVersionTypeComparison;

            var majorComparison = x.Major.CompareTo(y.Major);
            if (majorComparison != 0) return majorComparison;

            var minorComparison = x.Minor.CompareTo(y.Minor);
            if (minorComparison != 0) return minorComparison;

            var revisionComparison = x.Revision.CompareTo(y.Revision);
            if (revisionComparison != 0) return revisionComparison;

            var changeSetComparison = x.ChangeSet.CompareTo(y.ChangeSet);
            if (changeSetComparison != 0) return changeSetComparison;

            return 0;
        }
    }
}

#if !BANNERLORDBUTRSHARED_ENABLE_WARNINGS
#pragma warning restore
#endif
#nullable restore
#endif // BANNERLORDBUTRSHARED_DISABLE