// <auto-generated>
//   This code file has automatically been added by the "Bannerlord.BUTR.Shared" NuGet package (https://www.nuget.org/packages/Bannerlord.BUTR.Shared).
//   Please see https://github.com/BUTR/Bannerlord.BUTR.Shared for more information.
//
//   IMPORTANT:
//   DO NOT DELETE THIS FILE if you are using a "packages.config" file to manage your NuGet references.
//   Consider migrating to PackageReferences instead:
//   https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference
//   Migrating brings the following benefits:
//   * The "Bannerlord.BUTR.Shared/Helpers" folder and the "ModuleInfoHelper.cs" file don't appear in your project.
//   * The added file is immutable and can therefore not be modified by coincidence.
//   * Updating/Uninstalling the package will work flawlessly.
// </auto-generated>

#region License
// MIT License
// 
// Copyright (c) Bannerlord's Unofficial Tools & Resources
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#endregion

#if !BANNERLORDBUTRSHARED_DISABLE
#nullable enable
#pragma warning disable

namespace Bannerlord.BUTR.Shared.Helpers
{
    using ModuleInfo_ = global::Bannerlord.ModuleManager.ModuleInfoExtended;
    using LoadType_ = global::Bannerlord.ModuleManager.LoadType;
    using SubModuleInfo_ = global::Bannerlord.ModuleManager.SubModuleInfoExtended;
    using SubModuleTags = global::Bannerlord.ModuleManager.SubModuleTags;

    using global::Bannerlord.BUTR.Shared.Extensions;

    using global::System.Diagnostics;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.IO;
    using global::System.Text;
    using global::System.Reflection;
    using global::System.Xml;

    using global::TaleWorlds.Library;
    using global::TaleWorlds.MountAndBlade;

    using Module = TaleWorlds.MountAndBlade.Module;

#if !BANNERLORDBUTRSHARED_INCLUDE_IN_CODE_COVERAGE
    [ExcludeFromCodeCoverage, DebuggerNonUserCode]
#endif
    internal static class ModuleInfoHelper
    {
        private delegate string[] GetModulesNamesDelegate();

        private static readonly GetModulesNamesDelegate? GetModulesNames;

        private static readonly Type? _moduleHelperType = Type.GetType("TaleWorlds.ModuleManager.ModuleHelper, TaleWorlds.ModuleManager", false);
        private static readonly FieldInfo? _platformModuleExtensionField = _moduleHelperType?.GetField("_platformModuleExtension");

        private delegate object GetCurrentModuleDelegate();
        private static readonly Type? _moduleType = Type.GetType("TaleWorlds.MountAndBlade.Module, TaleWorlds.MountAndBlade", false);
        private static readonly GetCurrentModuleDelegate? GetCurrentModule;

        static ModuleInfoHelper()
        {
            var engineUtilitiesType =
                Type.GetType("TaleWorlds.Engine.Utilities, TaleWorlds.Engine", false);
            GetModulesNames =
                ReflectionHelper.GetDelegate<GetModulesNamesDelegate>(engineUtilitiesType?.GetMethod("GetModulesNames", BindingFlags.Public | BindingFlags.Static));

            GetCurrentModule =
                ReflectionHelper.GetDelegate<GetCurrentModuleDelegate>(_moduleType?.GetProperty("CurrentModule", BindingFlags.Public | BindingFlags.Static)?.GetMethod);
        }

        public static ModuleInfo_? LoadFromId(string id)
        {
            var path = GetPath(id);
            if (TryRead(path, out var xml))
            {
                var doc = new XmlDocument();
                doc.LoadXml(xml);
                return ModuleInfo_.FromXml(doc);
            }
            return null;
        }

        public static IEnumerable<ModuleInfo_> GetLoadedModules()
        {
            if (GetModulesNames == null) yield break;

            foreach (string modulesName in GetModulesNames())
            {
                if (LoadFromId(modulesName) is { } moduleInfo)
                    yield return moduleInfo;
            }
        }

        public static IEnumerable<ModuleInfo_> GetModules()
        {
            var list = new List<ModuleInfo_>();
            var physicalModules = GetPhysicalModules();
            var platformModules = GetPlatformModules();
            list.AddRange(physicalModules);
            list.AddRange(platformModules);
            var _allFoundModules = new Dictionary<string, ModuleInfo_>();
            foreach (var moduleInfo in list)
            {
                if (!_allFoundModules.ContainsKey(moduleInfo.Id.ToLower()))
                {
                    _allFoundModules.Add(moduleInfo.Id.ToLower(), moduleInfo);
                }
            }
            return list;
        }

        public static ModuleInfo_? GetModuleByType(Type type)
        {
            if (string.IsNullOrWhiteSpace(type.Assembly.Location))
                return null;

            var fullAssemblyPath= Path.GetFullPath(type.Assembly.Location);
            foreach (var loadedModule in GetLoadedModules())
            {
                var loadedModuleDirectory = Path.GetFullPath(Path.Combine(TaleWorlds.Engine.Utilities.GetBasePath(), "Modules", loadedModule.Id));
                var relativePath = new Uri(GetFullPathWithEndingSlashes(loadedModuleDirectory)).MakeRelativeUri(new Uri(fullAssemblyPath));
                if (!relativePath.OriginalString.StartsWith("../"))
                    return loadedModule;
            }

            return null;
        }

        private static string GetFullPathWithEndingSlashes(string input) =>
            $"{Path.GetFullPath(input).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)}{Path.DirectorySeparatorChar}";

        private static IEnumerable<ModuleInfo_> GetPhysicalModules()
        {
            foreach (string text in GetModulePaths(PathPrefix(), 1).ToArray<string>())
            {
                var directoryName = System.IO.Path.GetDirectoryName(text);
                var path = GetPath(Path.Combine(directoryName, "SubModule.xml"));
                if (TryRead(path, out var xml))
                {
                    var xmlDocument = new XmlDocument();
                    xmlDocument.Load(path);
                    yield return ModuleInfo_.FromXml(xmlDocument);
                }
            }
        }

        private static IEnumerable<ModuleInfo_> GetPlatformModules()
        {
            if (_moduleHelperType == null) yield break;
            if (_platformModuleExtensionField == null) yield break;

            var platformModuleExtension = _platformModuleExtensionField.GetValue(null);
            if (platformModuleExtension == null) yield break;

            var getModulePathsInvoker = platformModuleExtension.GetType().GetMethod("GetModulePaths", BindingFlags.Public | BindingFlags.Instance);
            if (getModulePathsInvoker == null) yield break;

            var modulePaths = getModulePathsInvoker.Invoke(platformModuleExtension, Array.Empty<object>()) as string[];
            if (modulePaths == null) yield break;

            foreach (string path in modulePaths)
            {
                if (TryRead(path, out var xml))
                {
                    var doc = new XmlDocument();
                    doc.LoadXml(xml);
                    yield return ModuleInfo_.FromXml(doc);
                }
            }
        }

        internal static IEnumerable<string> GetModulePaths(string directoryPath, int searchDepth)
        {
            if (searchDepth > 0)
            {
                foreach (string directories in Directory.GetDirectories(directoryPath))
                {
                    foreach (string path in GetModulePaths(directories, searchDepth - 1))
                    {
                        yield return path;
                    }
                }
            }
            foreach (string path in Directory.GetFiles(directoryPath, "SubModule.xml"))
            {
                yield return path;
            }
        }

        public static bool CheckIfSubModuleCanBeLoaded(SubModuleInfo_ subModuleInfo)
        {
            if (subModuleInfo.Tags.Count > 0)
            {
                foreach (var (key, values) in subModuleInfo.Tags)
                {
                    if (!Enum.TryParse<SubModuleTags>(key, out var tag))
                        continue;

                    foreach (var value in values)
                    {
                        if (!GetSubModuleTagValiditiy(tag, value))
                        {
                            return false;
                        }
                    }
                }
                return true;
            }
            return true;
        }

        public static bool GetSubModuleTagValiditiy(SubModuleTags tag, string value) => tag switch
        {
            SubModuleTags.RejectedPlatform => !Enum.TryParse<Platform>(value, out var platform) || ApplicationPlatform.CurrentPlatform != platform,
            SubModuleTags.ExclusivePlatform => !Enum.TryParse<Platform>(value, out var platform) || ApplicationPlatform.CurrentPlatform == platform,
            SubModuleTags.DependantRuntimeLibrary => !Enum.TryParse<Runtime>(value, out var runtime) || ApplicationPlatform.CurrentRuntimeLibrary == runtime,
            SubModuleTags.IsNoRenderModeElement => value.Equals("false"),
            SubModuleTags.DedicatedServerType => value.ToLower() switch
            {
                "none" => Module.CurrentModule.StartupInfo.DedicatedServerType == DedicatedServerType.None,
                "both" => Module.CurrentModule.StartupInfo.DedicatedServerType == DedicatedServerType.None,
                "custom" => Module.CurrentModule.StartupInfo.DedicatedServerType == DedicatedServerType.Custom,
                "matchmaker" => Module.CurrentModule.StartupInfo.DedicatedServerType == DedicatedServerType.Matchmaker,
                _ => false
            },
            _ => true
        };

        public static bool ValidateLoadOrder(Type subModuleType, out string report) => ValidateLoadOrder(GetModuleByType(subModuleType), out report);

        public static bool ValidateLoadOrder(ModuleInfo_ moduleInfo, out string report)
        {
            const string SErrorModuleNotFound = @"{=FE6ya1gzZR}{REQUIRED_MODULE} module was not found!";
            const string SErrorIncompatibleModuleFound = @"{=EvI6KPAqTT}Incompatible module {DENIED_MODULE} was found!";
            const string SErrorWrongModuleOrderTooEarly = @"{=5G9zffrgMh}{MODULE} is loaded before the {REQUIRED_MODULE}!{NL}Make sure {MODULE} is loaded after it!";
            const string SErrorWrongModuleOrderTooLate = @"{=UZ8zfvudMs}{MODULE} is loaded after the {REQUIRED_MODULE}!{NL}Make sure {MODULE} is loaded before it!";
            const string SErrorMutuallyExclusiveDirectives = @"{=FcR4BXnhx8}{MODULE} has mutually exclusive mod order directives specified for the {REQUIRED_MODULE}!";

            var loadedModules = ModuleInfoHelper.GetLoadedModules().ToList();
            var moduleIndex = loadedModules.IndexOf(moduleInfo);

            var sb = new StringBuilder();

            void ReportMissingModule(string requiredModuleId)
            {
                if (sb.Length != 0) sb.AppendLine();
                sb.AppendLine(TextObjectHelper.Create(SErrorModuleNotFound)
                    ?.SetTextVariable2("REQUIRED_MODULE", requiredModuleId)
                    ?.ToString() ?? "ERROR");
            }

            void ReportIncompatibleModule(string deniedModuleId)
            {
                if (sb.Length != 0) sb.AppendLine();
                sb.AppendLine(TextObjectHelper.Create(SErrorIncompatibleModuleFound)
                    ?.SetTextVariable2("DENIED_MODULE", deniedModuleId)
                    ?.ToString() ?? "ERROR");
            }

            void ReportLoadingOrderIssue(string reason, string requiredModuleId)
            {
                if (sb.Length != 0) sb.AppendLine();
                sb.AppendLine(TextObjectHelper.Create(reason)
                    ?.SetTextVariable2("MODULE", moduleInfo.Id)
                    ?.SetTextVariable2("REQUIRED_MODULE", requiredModuleId)
                    ?.SetTextVariable2("NL", Environment.NewLine)
                    ?.ToString() ?? "ERROR");
            }

            void ReportMutuallyExclusiveDirectives(string requiredModuleId)
            {
                if (sb.Length != 0) sb.AppendLine();
                sb.AppendLine(TextObjectHelper.Create(SErrorMutuallyExclusiveDirectives)
                    ?.SetTextVariable2("MODULE", moduleInfo.Id)
                    ?.SetTextVariable2("REQUIRED_MODULE", requiredModuleId)
                    ?.ToString() ?? "ERROR");
            }

            void ValidateDependedModuleCompatibility(int deniedModuleIndex, string deniedModuleId)
            {
                if (deniedModuleIndex != -1)
                {
                    ReportIncompatibleModule(deniedModuleId);
                }
            }

            void ValidateDependedModuleLoadBeforeThis(int requiredModuleIndex, string requiredModuleId, bool isOptional = false)
            {
                if (!isOptional && requiredModuleIndex == -1)
                {
                    ReportMissingModule(requiredModuleId);
                }
                else if (requiredModuleIndex > moduleIndex)
                {
                    ReportLoadingOrderIssue(SErrorWrongModuleOrderTooEarly, requiredModuleId);
                }
            }

            void ValidateDependedModuleLoadAfterThis(int requiredModuleIndex, string requiredModuleId, bool isOptional)
            {
                if (requiredModuleIndex == -1)
                {
                    if (!isOptional) ReportMissingModule(requiredModuleId);
                }
                else if (requiredModuleIndex < moduleIndex)
                {
                    ReportLoadingOrderIssue(SErrorWrongModuleOrderTooLate, requiredModuleId);
                }
            }

            foreach (var dependedModule in moduleInfo.DependentModules)
            {
                var module = loadedModules.SingleOrDefault(x => x.Id == dependedModule.Id);
                var dependedModuleIndex = module is not null ? loadedModules.IndexOf(module) : -1;
                ValidateDependedModuleLoadBeforeThis(dependedModuleIndex, dependedModule.Id);
            }
            foreach (var dependedModule in moduleInfo.DependentModuleMetadatas)
            {
                var module = loadedModules.SingleOrDefault(x => x.Id == dependedModule.Id);
                var dependedModuleIndex = module is not null ? loadedModules.IndexOf(module) : -1;

                if (dependedModule.IsIncompatible)
                {
                    if (moduleInfo.DependentModules.Any(dm => dm.Id == dependedModule.Id))
                    {
                        ReportMutuallyExclusiveDirectives(dependedModule.Id);
                        continue;
                    }
                    ValidateDependedModuleCompatibility(dependedModuleIndex, dependedModule.Id);
                }
                else if (dependedModule.LoadType == LoadType_.LoadBeforeThis)
                {
                    if (moduleInfo.DependentModules.Any(dm => dm.Id == dependedModule.Id)) continue;
                    ValidateDependedModuleLoadBeforeThis(dependedModuleIndex, dependedModule.Id, dependedModule.IsOptional);
                }
                else if (dependedModule.LoadType == LoadType_.LoadAfterThis)
                {
                    if (moduleInfo.DependentModules.Any(dm => dm.Id == dependedModule.Id) || (moduleInfo.DependentModuleMetadatas.Any(dm => dm.Id == dependedModule.Id && dm.LoadType == LoadType_.LoadBeforeThis)))
                    {
                        ReportMutuallyExclusiveDirectives(dependedModule.Id);
                        continue;
                    }
                    ValidateDependedModuleLoadAfterThis(dependedModuleIndex, dependedModule.Id, dependedModule.IsOptional);
                }
            }

            if (sb.Length > 0)
            {
                report = sb.ToString();
                return false;
            }

            report = null;
            return true;
        }


        private static string PathPrefix() => Path.Combine(TaleWorlds.Library.BasePath.Name, "Modules");
        private static string GetPath(string id) => Path.Combine(PathPrefix(), id, "SubModule.xml");

        private static bool TryRead(string path, out string? content)
        {
            try
            {
                using var xml = new StreamReader(path);
                content = xml.ReadToEnd();
                return true;
            }
            catch (Exception ex)
            {
                content = null;
                return false;

            }
        }
    }
}

#pragma warning restore
#nullable restore
#endif // BANNERLORDBUTRSHARED_DISABLE
